site_name: pyTigerGraph
nav:
    - 'Home': index.md
    - 'User Guide':
        - 'Getting Started': GettingStarted.md
        - 'Authentication': Auth.md
        - 'Core Functions': 
            - 'Overview': Functions.md
            - 'Schema Functions': SchemaFunctions.md
            - 'Vertex Functions': VertexFunctions.md
            - 'Edge Functions': EdgeFunctions.md
            - 'Query Functions': QueryFunctions.md
            - 'API Tokens': TokenManagement.md
            - 'Other Functions': OtherFunctions.md
        - 'DataFrame Functions': DataFrame.md
        - 'GSQL Functions': Gsql.md
    - Contribute: CONTRIBUTING.md
    - License: license.md
theme:
    name: material

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/parkererickson/pyTigerGraph